Ticket9
OneInfiniteLoops/newsspace pull request #6
Opened 2022-06-16 13:28 UTC by OneInfiniteLoops

This pull request commits the following:
- add getUsers request to api.js
- add UsersList component to render a list of usernames and select buttons
- add a link to switch user profile page (/users) on the navbar
- add a new route to switch user profile
- create UserContext
- displays the current user from UserContext on the header
- Add a page for SwitchUserProfile which renders UsersList
- Add postCommentByArticleID request to API
- Set the initial state for user to an empty string as default in the app
- Add CommentForm component as a child of CommentsList which allows for posting comment by user with appropriate feedback

2022-06-16 13:55 UTC, popatre requested changes
As well as the other comment - if im not signed in, it still lets me type in the form and says 'posted successful'. 
Although it doesnt add the comment, as a user, it appears like ive posted something

2022-06-16 13:55 UTC, popatre commented on src/components/CommentForm.jsx
> +        <h2>Comment Posted Successfully!</h2>
It would be good to also see the comment in the list after posting. At the moment i have to refresh to see what i wrote.

2022-06-16 15:24 UTC, Rosem10 requested changes
This is generally really nice, although if I click to login as one of the users > post a comment > refresh the page - it then behaves as if I have logged out. Also the added comment moves from the top of the list to the bottom on if you leave the page and come back, and it would be nicer UX if it was consistent.

2022-06-16 15:58 UTC, popatre approved these changes
Seems much better - although if you add a signout button at any point, you'd need to test the form doesnt still do the think it was doing before

2022-06-17 08:21 UTC, OneInfiniteLoops commented
The latest commit also includes the addition of a functional sign-out button on the switch user page.

2022-06-17 09:47 UTC, hevdevs commented
All seems working as intended now - nice one! Only thing I'd consider is that you may want to set the default user to not being signed in as jessjelly so that the user is forced to use the sign in functionality (I know right now you might want to be signed in as default just for ease of navigating your website whilst getting functionality nailed down, which is totes fine)

2022-06-17 10:10 UTC, scar1377 reviewed
Hi James. The code looks good. Only a couple of suggestions -
1. Using textarea over input to allow multiple lines 
2. Might be a good idea to keep the post section in case the users want to post another comment

2022-06-17 10:26 UTC, popatre approved these changes

2022-06-17 10:36 UTC, merged